### ISSUE TITLE
请问能公布原理图吗？

### ISSUE THREAD

**Issue by duoffice** [sillyhatday/GAMEBOY-FLASHCART-MBC5#2]
一直想找MBC3和MBC5卡带的原理图，请问能开源原理图吗？谢谢

**Comment by sillyhatday** [comment]
Please comment in English

**Comment by duoffice** [comment]
Sorry, My English is poor. I have been looking for the schematic diagram of MBC3 and MBC5 Card. Could you please open source the schematic diagram? thank you。

**Comment by sillyhatday** [comment]
Your English is good. I may release it. There are others that have released schematics already.
