### ISSUE TITLE
Use of am29f032

### ISSUE THREAD

**Issue by P-C-R** [sillyhatday/GAMEBOY-FLASHCART-MBC5#4]
Would the am29f032 work aswell?

**Comment by sillyhatday** [comment]
One is a 48 pin and one is a 40 pin. You could line up the 29F032 to work, then tie the extra address line to ground. It's only a 2MB board layout, so you don't gain anything using the 4MB ROM.

**Comment by P-C-R** [comment]
Thank you. I am still struggling to flash one. One is aborted while
eareasing. The other at 7 percent flash. I suspect bad EPROM..... Do you
ever encounter that?

sillyhatday ***@***.***> schrieb am Mi., 22. Feb. 2023, 08:24:

**Comment by sillyhatday** [comment]
Possible bad EEPROM. I've solved this sort of issue each time by checking the solder joints on the MBC and EEPROM. The EEPROM is awfully tricky to get right hand soldering.
