### ISSUE TITLE
Orientation of Flash and FRAM

### ISSUE THREAD

**Issue by P-C-R** [sillyhatday/GAMEBOY-FLASHCART-MBC5#5]
Can you add to the Gerber the Orientation? 
I figured it out with the schematic but want to double check. 

I built one board but can not be flashed. Will have to investigate it

**Comment by sillyhatday** [comment]
Glad to hear someone has made some. The chip outlines have a longer line that is next to pin 1. These are the default chip markings. I could add something to make it more clear.

**Comment by P-C-R** [comment]
Can be closed. Even inused a stencil + mask i resolderd all joints by hand with the help of a lot of flux. Worked
