### ISSUE TITLE
Does the 4MB chip not work?

### ISSUE THREAD

**Issue by duoffice** [sillyhatday/GAMEBOY-FLASHCART-MBC5#7]
Hello, I use ST's M29F032D chip, burn 4M games, every time the test will report an error. The game doesn't work properly. But if I use this chip to burn 2M games, there is no problem, is it the design of the cassette can not burn 4M capacity? Is it a lack of chips?

**Comment by sillyhatday** [comment]
It's only for 2MB (16Mbit) ROMs. I admit I should make that more clear and add a proper bill of materials. The pin out will fit a 29F032 but it's not setup to support the extra address line.
