### ISSUE TITLE
Support for Sram instead of FRAM

### ISSUE THREAD

**Issue by DevDavisNunez** [sillyhatday/GAMEBOY-FLASHCART-MBC5#9]
Could there be a possibility that the design includes the SRAM and a battery instead of the old and expensive FRAMs?
I searched a lot on sales sites, but they all seem to have defects if they cost less than $12 dollars, so it would seem like a better option to use the same sram (256kb) of the donor cartridge,
And thank you very much for sharing your excellent work ;)

**Comment by sillyhatday** [comment]
Sorry I missed your issue. I have an SRAM version that I can share but there are now much better designs from Mousebitelabs who has done MBC1, MBC3 and MBC5 all with SRAM.
